.TH JUFFED "1" "November 2009" "@VERSION@" "User Commands"

.SH NAME
JuffEd - Qt 4 based text editor

.SH DESCRIPTION
.B JuffEd
is a simple, cross-platform text editor written using the Qt 4 toolkit
 and the QScintilla library. It supports most features found in modern text
 editors, including syntax highlighting, bracket matching, switching encodings,
 sessions, and a plugin API.
.PP
.B JuffEd
has no command line options. Please run it under X.

.SH SYNOPSIS
.B juffed

.SH OPTIONS
.B juffed
has no options.

.SH "SEE ALSO"
Homepage: http://juffed.com

.SH AUTHOR
This manual page was written by Maia Kozheva <sikon@ubuntu.com> for the Debian system (but may be used by others).
.br
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, version 2 or any later version published by the Free Software Foundation
.br
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
