/*
This file was automatically generated by configure script.
All the changes you made will be lost after the next run
of configure script.
*/

#ifndef _APP_INFO_H_
#define _APP_INFO_H_

#include <QtCore/QDir>
#include <QtCore/QString>

class AppInfo {
public:
        static QString name() { return "JuffEd"; }
        static QString organization() { return "Juff"; }
        static QString configDir() { return QDir::homePath() + "/.config/" + organization().toLower(); }
        static QString configFile() { return configDir() + "/" + name().toLower() + ".conf"; }
        static QString version() { return "@JUFFED_VERSION@"; }
        static QString logFile() { return configDir() + "/juffed.log"; }
        static QString socketPath() { return "/tmp/juffed"; }
        static QString appDirPath() { return "@DATA_INSTALL_DIR@"; }
};

#endif