/*
This file was automatically generated by configure script.
All the changes you made will be lost after the next run
of configure script.
*/

#ifndef _APP_INFO_NIX_H_
#define _APP_INFO_NIX_H_

#include <QtCore/QDir>
#include <QtCore/QLocale>
#include <QtCore/QString>


class AppInfo {
public:
	static QString name()            { return "JuffEd"; }
	static QString organization()    { return "Juff"; }
	static QString configDirPath()   { return QDir::homePath() + "/.config/" + organization().toLower(); }
	static QString configFile()      { return configDirPath() + "/" + name().toLower() + ".conf"; }
	static QString translationPath() { return appDirPath() + "/l10n"; }
	static QString version()         { return "@JUFFED_VERSION@"; }
	static QString logFile()         { return configDirPath() + "/juffed.log"; }
	static QString language()        { return QLocale::system().name(); }
	static QString defaultPrjPath()  { return configDirPath() + "/empty_project.xml"; }
	
	static QString appDirPath()      { return "@DATA_INSTALL_DIR@"; }
};

#endif
