name: CI Linux

on: [push, pull_request]

jobs:
  linux-build:
    strategy:
      fail-fast: false
      matrix:
        m:
        - { os: ubuntu-24.04-arm, configuration: Release, arch: armv7 }
        - { os: ubuntu-24.04-arm, configuration: Release, arch: aarch64 }
#        - { os: ubuntu-20.04, configuration: Release, arch: i386 }
        - { os: ubuntu-24.04, configuration: Release, arch: amd64 }
#        - { os: ubuntu-20.04, configuration: Debug, arch: i386 }
        - { os: ubuntu-24.04, configuration: Debug, arch: amd64 }
    runs-on: ${{matrix.m.os}}
    name: 'Linux ${{matrix.m.configuration}} ${{matrix.m.arch}}'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Save current datetime
      id: date
      run: echo "date=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT

    - name: amd64 | Install libs
      if: matrix.m.arch == 'amd64'
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build qtbase5-dev qttools5-dev libqscintilla2-qt5-dev libqtermwidget5-1-dev libutf8proc-dev

    - name: i386 | Install libs
      if: matrix.m.arch == 'i386'
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get remove libutf8proc2
        sudo apt-get update
        sudo apt-get -y install --allow-downgrades libpcre2-8-0=10.34-7 # fix CI error https://github.com/actions/virtual-environments/issues/4620
        # additional i386 packages:
        sudo apt-get install libqt5help5:i386 libqt5designercomponents5:i386 libqt5designer5:i386 libqscintilla2-qt5-l10n
        # real packages:
        sudo apt-get install gcc-multilib g++-multilib cmake ninja-build qtbase5-dev:i386 qttools5-dev:i386
        # libqscintilla2-qt5-dev:i386 and libqtermwidget5-0-dev:i386 is missing in ubuntu 20.04, will take it from launchpad
        mkdir i386 && cd i386
        curl -LJO https://github.com/q4a/juffed/releases/download/i386-deps/libqscintilla2-qt5-15_2.11.2+dfsg-5_i386.deb
        curl -LJO https://github.com/q4a/juffed/releases/download/i386-deps/libqscintilla2-qt5-dev_2.11.2+dfsg-5_i386.deb
        curl -LJO https://github.com/q4a/juffed/releases/download/i386-deps/libqtermwidget5-0-dev_0.14.1-0ubuntu3_i386.deb
        curl -LJO https://github.com/q4a/juffed/releases/download/i386-deps/libqtermwidget5-0_0.14.1-0ubuntu3_i386.deb
        curl -LJO https://github.com/q4a/juffed/releases/download/i386-deps/libutf8proc-dev_2.4.0-2build1_i386.deb
        curl -LJO https://github.com/q4a/juffed/releases/download/i386-deps/libutf8proc2_2.4.0-2build1_i386.deb
        curl -LJO https://github.com/q4a/juffed/releases/download/i386-deps/qtermwidget5-data_0.14.1-0ubuntu3_all.deb
        sudo dpkg -i *.deb

    - name: Debug amd64 | Configure with cmake
      if: matrix.m.configuration == 'Debug' && matrix.m.arch == 'amd64'
      run: mkdir build && cd build && cmake .. -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.m.configuration}}

    - name: Debug i386 | Configure with cmake
      if: matrix.m.configuration == 'Debug' && matrix.m.arch == 'i386'
      run: mkdir build && cd build && CXXFLAGS="-m32" cmake .. -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.m.configuration}}

    - name: Debug | Build with cmake
      if: matrix.m.configuration == 'Debug'
      run: ninja
      working-directory: build

    - name: Release amd64 | Build deb packages with debuild
      if: matrix.m.configuration == 'Release' && matrix.m.arch == 'amd64'
      run: |
        sudo apt-get install devscripts debhelper libenca-dev build-essential
        debuild -b -uc -us

    - name: Release i386 | Build deb packages with cross-config + dpkg-buildpackage
      if: matrix.m.configuration == 'Release' && matrix.m.arch == 'i386'
      run: |
        sudo apt-get install build-essential crossbuild-essential-i386 debhelper
        # libenca-dev:i386 is missing in ubuntu 20.04, will take it from launchpad
        mkdir x86 && cd x86
        curl -LJO https://github.com/q4a/juffed/releases/download/i386-deps/libenca-dev_1.19-1_i386.deb
        curl -LJO https://github.com/q4a/juffed/releases/download/i386-deps/libenca0_1.19-1_i386.deb
        sudo dpkg -i *.deb
        cd ..
        CONFIG_SITE=/etc/dpkg-cross/cross-config.amd64 DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -Pcross,nocheck -ai386 -b -uc -us

    - name: armv7, aarch64 | Install libs and build with dpkg-buildpackage
      if: matrix.m.arch == 'armv7' || matrix.m.arch == 'aarch64'
      uses: uraimo/run-on-arch-action@v3
      with:
        arch: ${{matrix.m.arch}}
        distro: ubuntu20.04
        # GitHub token used for caching Docker images in project's public package registry
        githubToken: ${{github.token}}
        # Mount the juffed directory as /artifacts in the container
        dockerRunArgs: |
          --volume "/home/runner/work/juffed:/artifacts"
        # Install dependencies in the container. They will be cached
        install: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -q -y
          # Install cmake >=3.18 to fix for cmake bug on qemu+armhf: https://gitlab.kitware.com/cmake/cmake/-/issues/20568
          if [ "${{matrix.m.arch}}" = "armv7" ]; then
            apt-get install -q -y gpg wget
            wget --no-check-certificate https://apt.kitware.com/ubuntu/pool/main/c/cmake/cmake_3.20.5-0kitware1ubuntu20.04.1_armhf.deb
            wget --no-check-certificate https://apt.kitware.com/ubuntu/pool/main/c/cmake/cmake-data_3.20.5-0kitware1ubuntu20.04.1_all.deb
            dpkg -i cmake*.deb
          fi
          apt-get install -q -y gcc g++ cmake ninja-build qtbase5-dev qttools5-dev libqscintilla2-qt5-dev libqtermwidget5-0-dev libutf8proc-dev
          # Install debuild dependencies
          apt-get install -q -y pkg-config devscripts debhelper libenca-dev
        run: |
          cmake --version
          # Will use regular dpkg-buildpackage instead of debuild because of this bug: https://bugs.launchpad.net/cloud-images/+bug/1881217
          #debuild -b -uc -us
          dpkg-buildpackage -b -uc -us
          cp ../*.deb /artifacts

    - name: Release | Upload deb packages
      if: matrix.m.configuration == 'Release'
      uses: actions/upload-artifact@main
      with:
        name: ubuntu-release-${{matrix.m.arch}}-deb-files-${{steps.date.outputs.date}}
        path: /home/runner/work/juffed/*.deb # ../*.deb - but relative pathing is not allowed.
